<Project>
  <PropertyGroup>
    <IsTestProject Condition="'$(IsTestProject)' == ''">true</IsTestProject>
    <IsFunctionalTest>true</IsFunctionalTest>

    <SkipTestUtilitiesReference>true</SkipTestUtilitiesReference>
    <SkipXunitTrimmerDescriptor>true</SkipXunitTrimmerDescriptor>
  </PropertyGroup>

  <PropertyGroup>
    <RunAnalyzers>false</RunAnalyzers>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BrowserHost)' != 'windows'">
    <ExecXHarnessCmd>$HARNESS_RUNNER</ExecXHarnessCmd>
    <XHarnessOutput>$XHARNESS_OUT</XHarnessOutput>
  </PropertyGroup>

  <PropertyGroup Condition="'$(BrowserHost)' == 'windows'">
    <ExecXHarnessCmd>%HARNESS_RUNNER%</ExecXHarnessCmd>
    <XHarnessOutput>%XHARNESS_OUT%</XHarnessOutput>
  </PropertyGroup>

  <Import Condition="'$(IsFunctionalTest)' != 'true'" Project="..\Directory.Build.props"/>

  <!-- Opt-in to libraries build setup -->
  <Import Condition="'$(IsFunctionalTest)' == 'true'" Project="..\..\libraries\Directory.Build.props" />
</Project>
